# Generated by Django 4.0.3 on 2022-04-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bolg',
            new_name='Blog',
        ),
    ]
